# Generated by Django 3.1.2 on 2020-10-25 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='digitalpessoa',
            table='digital_usuario',
        ),
    ]
