# Generated by Django 3.1.2 on 2020-11-07 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201024_2241'),
    ]

    operations = [
        migrations.RenameField(
            model_name='digitalpessoa',
            old_name='impress_dig',
            new_name='foto_impress_dig',
        ),
        migrations.AddField(
            model_name='digitalpessoa',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterModelTable(
            name='digitalpessoa',
            table='Digital',
        ),
    ]
