# Generated by Django 3.1.2 on 2020-11-09 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201106_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitalpessoa',
            name='foto_impress_dig',
            field=models.ImageField(upload_to='digital'),
        ),
    ]
